<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Dto\" />
    <Folder Include="Constants\" />
    <Folder Include="Wrappers\" />
    <Folder Include="Query\" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="AutoMapper" Version="12.0.0" />
	  <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
	  <PackageReference Include="FluentValidation" Version="12.0.0" />
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
	  <PackageReference Include="MediatR" Version="13.0.0" />
	  <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
	  <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PmtAdmin.Domain\PmtAdmin.Domain.csproj" />
	<ProjectReference Include="..\PmtAdmin.Infrastructure\PmtAdmin.Infrastructure.csproj" />
  </ItemGroup>

</Project>
